remote_theme: https://github.com/just-the-docs/just-the-docs
title: ğŸ§ PenguinMails Documentation
description: This documentation hub helps you understand, manage, and scale PenguinMails. Whether youâ€™re making strategic decisions, designing user experiences, or coordinating technical development, find your path below.
markdown: GFM
mermaid:
  version: "11.12.1"
aux_links:
  "Repo on GitHub":
    - "https://github.com/penguinmails/penguinmails.github.io"
